version: '3'
services:
    apiv1:
        container_name: api-v1
        build: ./api/v1
        ports:
            - 7070:7070
    apiv2:
        container_name: api-v2
        build: ./api/v2
        ports:
            - 7080:7080
