version: '3'
services:
  nextcloud01:
    image: nextcloud:21.0.0-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    networks:
      hcc:
        ipv4_address: 172.26.0.11

  nextcloud02:
    image: nextcloud:21.0.0-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    networks:
      hcc:
        ipv4_address: 172.26.0.12

  nextcloud03:
    image: nextcloud:21.0.0-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    networks:
      hcc:
        ipv4_address: 172.26.0.13

  mariadb:
    image: mariadb:10.4.8-bionic
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      hcc:
        ipv4_address: 172.26.0.3

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      hcc:
        ipv4_address: 172.26.0.4

volumes:
  nextcloud:
  db:

networks:
  hcc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16