version: '3'
services:
  nextcloud1:
    image: nextcloud:21.0.0-apache
    container_name: servicio_nextcloud1_75570479
    restart: always
    volumes:
      - nextcloud_75570479:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS='localhost' 'hadoop.ugr.es'
    networks:
      hcc:
        ipv4_address: 172.26.0.11

  nextcloud2:
    image: nextcloud:21.0.0-apache
    container_name: servicio_nextcloud2_75570479
    restart: always
    volumes:
      - nextcloud_75570479:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS='localhost' 'hadoop.ugr.es'
    networks:
      hcc:
        ipv4_address: 172.26.0.12

  nextcloud3:
    image: nextcloud:21.0.0-apache
    container_name: servicio_nextcloud3_75570479
    restart: always
    volumes:
      - nextcloud_75570479:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_TRUSTED_DOMAINS='localhost' 'hadoop.ugr.es'
    networks:
      hcc:
        ipv4_address: 172.26.0.13

  mariadb:
    image: mariadb:10.4.8-bionic
    container_name: servicio_mariadb_75570479
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_75570479:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      hcc:
        ipv4_address: 172.26.0.3

  nginx:
    image: nginx:alpine
    container_name: servicio_nginx_75570479
    restart: always
    ports:
      - 31013:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      hcc:
        ipv4_address: 172.26.0.4

  ldap:
    image: larrycai/openldap
    container_name: servicio_ldap_75570479
    restart: always
    volumes:
      - ./more.ldif:/more.ldif
    networks:
      hcc:
        ipv4_address: 172.26.0.5

volumes:
  nextcloud_75570479:
  db_75570479:

networks:
  hcc:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16