version: '3'
services:
    mongodb:
        container_name: mongodb
        image: mongo:3.2.6
        ports:
            - 27017:27017
        volumes:
            - .:/csvdata
        command: mongoimport  --db p2 --collection sanfrancisco --type csv --headerline --file /csvdata/sanfrancisco.csv
