version: '3'
services:
    mongodb:
        container_name: mongodb
        image: mongo:3.2.6
        ports:
            - 27017:27017
        volumes:
            - .:/csvdata

    mongo_seed:
        image: mongo:3.2.6
        links:
            - mongodb
        volumes:
            - .:/mongo-seed
        command: /mongo-seed/import.sh
